### ISSUE TITLE
(Question) This language is GPU-agnostic?

### ISSUE THREAD

**Issue by hardBSDk** [HigherOrderCO/Bend#393] opened 2024-05-19 03:19 UTC
Does it run on any GPU? be it Intel, AMD, NVIDIA or ARM?

**Comment by SquarishRectangle** [comment] 2024-05-19 04:03
Not completely sure what's going on behind the scenes but the documentation currently only lists a CUDA runtime for GPUs.

**Comment by developedby** [comment] 2024-05-19 11:12
The language is GPU agnostic, but currently we only have a CUDA runtime. So only Nvidia gpus are supported, but we plan on adding other gpus in the future.
Duplicate of https://github.com/HigherOrderCO/Bend/issues/341

**Closed by developedby** 2024-05-19 11:12 UTC
Labels: question
