### ISSUE TITLE
CUDA not available! even if it is installed

### ISSUE THREAD

**Issue by edoelas** [HigherOrderCO/Bend#342] opened 2024-05-17 21:23 UTC
**Describe the bug**
When running a program with `bend run-cu` it says:
```
Error reading result from hvm. Output :
CUDA not available!
```
I just installed CUDA on WSL following the nvidia guide and the command `nvcc --version` works fine on the same terminal I am running bend. I followed the guide on the README to install bend.

**To Reproduce**
Run a program with cuda.

**Expected behavior**
I expect the program to run.

**Desktop (please complete the following information):**
 - OS:   [5.15.146.1-microsoft-standard-WSL2]
 - CPU: [e.g. AMD ryzen 9 7900]
 - GPU: [e.g. RTX 4070]
 - Cuda Version [release 12.4, V12.4.131]

**Terminal output**
```
~$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Thu_Mar_28_02:18:24_PDT_2024
Cuda compilation tools, release 12.4, V12.4.131
Build cuda_12.4.r12.4/compiler.34097967_0
~$ bend run-cu test.bend 
Errors:
Error reading result from hvm. Output :
CUDA not available!
```

**Comment by kings177** [comment] 2024-05-17 21:50
thank you for the issue, i'm moving this to HVM as this is related to HVM, and a duplicate of https://github.com/HigherOrderCO/HVM/issues/283

**Closed by kings177** 2024-05-17 21:50 UTC
Labels: bug
