### ISSUE TITLE
(Request) Document or Expose a C FFI

### ISSUE THREAD

**Issue by e-dant** [HigherOrderCO/Bend#396] opened 2024-05-19 05:26 UTC
**A language is incomplete until Doom has been written in it.**
A doom implementation is a sign of maturity and interest in a language or technology. Popular tools like htop and routines like printf run Doom. 
Doomgeneric has a C API. 
It is easier to port Doom to systems that expose a C FFI. 

**Describe the solution you'd like**
Implementing or exposing and documenting a C FFI. 

**Describe alternatives you've considered**
I have explored the documentation but haven't found a native way to call into a C ABI-compatible interface.

**Comment by developedby** [comment] 2024-05-19 11:39
Duplicate of #350

**Closed by developedby** 2024-05-19 11:39 UTC
Labels: enhancement
