### ISSUE TITLE
Failed installation on wsl Windows 11

### ISSUE THREAD

**Issue by UsmanTariq2** [HigherOrderCO/Bend#355] opened 2024-05-18 03:17 UTC
**Describe the bug**
`   Updating crates.io index
  Installing hvm v2.0.8
    Updating crates.io index
     Locking 29 packages to latest compatible versions
   Compiling libc v0.2.155
   Compiling utf8parse v0.2.1
   Compiling anstyle v1.0.7
   Compiling anstyle-query v1.0.3
   Compiling is_terminal_polyfill v1.70.0
   Compiling colorchoice v1.0.1
   Compiling clap_lex v0.7.0
   Compiling strsim v0.11.1
   Compiling anstyle-parse v0.2.4
   Compiling cc v1.0.97
   Compiling highlight_error v0.1.1
   Compiling TSPL v0.0.12
   Compiling anstream v0.6.14
error: linker `cc` not found
  |
  = note: No such file or directory (os error 2)

error: could not compile `libc` (build script) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `hvm v2.0.8`, intermediate artifacts can be found at `/tmp/cargo-installz7F0B2`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.`

**To Reproduce**
1. Latest windows and WSL 2
2. Use command cargo +nightly install hvm

**Comment by 54g0** [comment] 2024-05-18 06:22
Solution for linkercc not found Error on WSLThe error message linkercc not found indicates that the cc compiler (part of the build-essential package) is not installed or not available in your WSL environment. To resolve this error, follow these steps:
1.Update and Upgrade Your System:
sudo apt update
sudo apt upgrade -y
2.Install the Build-Essential Package:
sudo apt install build-essential -y
3.Ensure pkg-config is Installed:
sudo apt install pkg-config -y
4.Retry the Installation: Try to install hvm again
cargo +nightly install hvm
5.Ensure Rust is Installed Correctly: Ensure that Rust and the nightly toolchain are set up correctly in your WSL environment:
rustup update
rustup toolchain install nightly
rustup default nightly
If any other specific errors come up, please provide those details.

**Comment by RagnaJok** [comment] 2024-05-18 10:13
Got the same error but upgrading the system fixed it,
write: 
sudo apt-get update 
before 
sudo apt update 
and you can retry the installation of hvm

Thanks 54g0 :))

**Comment by kings177** [comment] 2024-05-18 16:00
what @54g0 said is correct @UsmanTariq2, the problem is that you're missing the `libc` package , which comes with `build-essential`, i recommend installing `build-essential` as that will also give you gcc, in case you don't have it, you can install it with `sudo apt install build-essential`.

**Comment by UsmanTariq2** [comment] 2024-05-19 02:46
Hey,  installing build-essential solved the problem
I generally dont install it because it has older versions of g++ installed, and i was under the impresssion that installing g++ installs everything. Manually using latest compiler with build-essential. So on me.

**Comment by kings177** [comment] 2024-05-19 02:48
glad to know it worked :)

**Comment by UsmanTariq2** [comment] 2024-05-19 02:50
Also,
when i run the command 

> bend run    <file.hvm> # uses the Rust interpreter (sequential)

`bash: syntax error near unexpected token `newline'`

Typo?

**Comment by kings177** [comment] 2024-05-19 03:02
assuming you typed the full `bend run <file.hvm> # uses the Rust interpreter (sequential)`.

you're supposed to type an actual path to a file instead of `<file.hvm>`, so like, for example, you can create a file called `test.bend` with the following content:

```python
def main:
  list = [1, 2, 3]
  return list
```

then just do `bend run-c test.bend`

**Comment by UsmanTariq2** [comment] 2024-05-19 03:03
Get an error when compiling the sorter example:

> Error reading result from hvm. Output :
> signal: 11 (SIGSEGV)

**.out.hvm :**

`@down = (?(((a (* a)) @down__C0) (b (c d))) (c (b d)))

@down__C0 = ({a e} ((c g) ({b f} (d h))))
  &! @rots ~ (a (b (c d)))
  &! @rots ~ (e (f (g h)))

@gen = (?(((a a) @gen__C0) b) b)

@gen__C0 = ({a d} ({$([*2] $([+1] b)) $([*2] e)} (c f)))
  &! @gen ~ (a (b c))
  &! @gen ~ (d (e f))

@main = a
  & @sum ~ (18 (@main__C1 a))

@main__C0 = a
  & @gen ~ (18 (0 a))

@main__C1 = a
  & @sort ~ (18 (0 (@main__C0 a)))

@rots = (?(((a (* a)) @rots__C0) (b (c d))) (c (b d)))

@rots__C0 = ({$([+1] a) c} ((e f) ({b d} h)))
  & @down ~ (a (b (g h)))
  & @warp ~ (c (d (e (f g))))

@sort = (?(((a (* a)) @sort__C0) (b (c d))) (c (b d)))

@sort__C0 = ({$([+1] a) {f c}} ((d g) (b i)))
  & @rots ~ (a (b (e (h i))))
  &! @sort ~ (c (0 (d e)))
  &! @sort ~ (f (1 (g h)))

@sum = (?(((a a) @sum__C0) b) b)

@sum__C0 = ({a c} ((b d) f))
  &! @sum ~ (a (b $(:[+] $(e f))))
  &! @sum ~ (c (d e))

@swap = (?((@swap__C0 @swap__C1) (a (b c))) (b (a c)))

@swap__C0 = (b (a (a b)))

@swap__C1 = (* (a (b (a b))))

@warp = (?((@warp__C0 @warp__C1) (a (b (c d)))) (c (b (a d))))

@warp__C0 = ({a e} ({$(:[>] $(a b)) d} ($(:[+] $(b c)) f)))
  & @swap ~ (c (d (e f)))

@warp__C1 = ({a f} ((d i) ((c h) ({b g} ((e j) (k l))))))
  &! @warp ~ (f (g (h (i (j l)))))
  &! @warp ~ (a (b (c (d (e k)))))`

**Comment by kings177** [comment] 2024-05-19 03:18
can you type `free -h` and paste me the output please?

**Comment by UsmanTariq2** [comment] 2024-05-19 03:34
`               total        used        free      shared  buff/cache   available
Mem:           3.8Gi       668Mi       3.2Gi       660Ki        72Mi       3.1Gi
Swap:          1.0Gi       697Mi       326Mi`

**Comment by kings177** [comment] 2024-05-20 13:38
do you get this error everytime you run something with `run-c`? even if you run something like 

```py
def main:
  return "test"
```

**Comment by kings177** [comment] 2024-05-22 21:15
Closing this since the issue has been fixed and now there has been another issue that falls under https://github.com/HigherOrderCO/Bend/issues/397 and https://github.com/HigherOrderCO/HVM/issues/309

**Closed by kings177** 2024-05-22 21:15 UTC
Labels: help wanted
