### ISSUE TITLE
Bend malfunctions when two lists are declared

### ISSUE THREAD

**Issue by arpheno** [HigherOrderCO/Bend#424] opened 2024-05-21 09:07 UTC
**Describe the bug**
When I have an unused list in addition to a used list, the program doesn't terminate correctly sometimes:

**To Reproduce**
1. Running command `bend run-c bug.bend`
2. With code
```
def map(fn, list):
  fold list:
    case List/Cons:
      return List/Cons(fn(list.head), list.tail)
    case List/Nil:
      return []

def tt(x):
  return x*2

def main():
  l = [5,6,7,8]
  k = [1,2,3,4]
  return map(tt,l)
```
4. Error...
```
bend run-c bug.bend  
Result: (map tt [5, 6, 7, 8])
```
**Expected behavior**
```
bend run bug.bend  
Result: [10, 12, 14, 16]
```

**Desktop (please complete the following information):**
 - OS:   Apple M1
 - CPU: Apple M1
 - GPU: ?
 - Cuda Version ?

**Additional context**
This code works fine:
```
def map(fn, list):
  fold list:
    case List/Cons:
      return List/Cons(fn(list.head), list.tail)
    case List/Nil:
      return []

def tt(x):
  return x*2

def main():
  l = [5,6,7,8]
  # k = [1,2,3,4]
  return map(tt,l)
 ```
I can't reproduce it but i swear i had the same issue even when not using run-c

**Comment by developedby** [comment] 2024-05-21 09:58
When you add the second list it's causing the `map(tt, [5,6,7,8])` part to be converted into a lazy reference which is not evaluated.
However we can't simply expand everything since infinite terms (recursive) will loop forever.

So it's a hard problem and I haven't found the right amount of reference expanding that needs to be done to meet user expectation.

For now maybe I'll add one layer of expansion to `main` and it should solve most of the issues people encounter

**Comment by arpheno** [comment] 2024-05-21 12:06
How can I make sure I don't encounter the problem? I still don't know what I did to cause this.
Currently it feels like it's really easy to induce this behaviour.

**Comment by developedby** [comment] 2024-05-21 22:28
I've implemented this, but the solution (expanding terminal references in main, not extracting combinators from main), but it's giving me unexpected behaviour changes in some programs, so I'm investigating that first before merging the fix.

**Comment by FranciscoJavierPizarro** [comment] 2024-06-04 12:39
Hi i just want to expand the original scope of this issue,

this its not just a problem with the lists its a lazy eval problem when a var is defined but not used

For example the code
```
def simplefunc(a,b):
  return a + b
def main():
  a = 1
  b = 5
  c = 7
  return simplefunc(a,b)
```
should return `Result: 6` but instead returns `Result: (simplefunc 1 5)`

A possible (but maybe not easy of implementing) fix should be have a register of the number of apparitions of each symbol in the symboltable, in this example:

```
a | 2
b | 2
c | 1
```

As `c` does only have 1 apparition in the function scope we know its just being defined and is not being used anywhere else

**Comment by developedby** [comment] 2024-06-04 12:44
@FranciscoJavierPizarro as I mentioned, I already have a fix for this, but it sometimes triggers a bug in the HVM, so I'm waiting for it to be fixed first.
It'll take care of all these simple cases where main is basically just a call to another function (and some others as well).

**Closed** 2024-06-05 17:31 UTC
Labels: bug, compilation
