### ISSUE TITLE
How to interface Bend code with my program/language?

### ISSUE THREAD

**Issue by sheharyarn** [HigherOrderCO/Bend#407] opened 2024-05-20 02:16 UTC
Bend looks like an amazing project. I want to try replacing certain parts of my existing code with a Bend implementation. Is there a way/documentation to currently do this?

Similar to how you can call C code from many languages like Python, Java, Erlang, Elixir.

**Comment by fzn0x** [comment] 2024-05-20 02:24
Bend still in _very_ early stage, I think isn't advisable to migrate your project code to Bend. Many wider language supports is still not supported in Bend.

For HVM2, it is production-ready now.

You can check https://github.com/HigherOrderCO/Bend/blob/main/FEATURES.md for what's supported. Also check their Discord for more announcements.

**Comment by sheharyarn** [comment] 2024-05-20 03:14
> Bend still in very early stage, I think isn't advisable to migrate your project code to Bend. 

Lol yes the plan isn't to do that for a production codebase, but just to experiment with code integration in one my side projects.

**Comment by developedby** [comment] 2024-05-20 08:26
We plan on adding it soon, right after we add IO, please wait a little bit.
Duplicate of #350

**Closed by developedby** 2024-05-20 08:26 UTC
