### ISSUE TITLE
A Name needs to use .to_string() before comparing to a String.

### ISSUE THREAD

**Issue by vkobinski** [HigherOrderCO/Bend#536] opened 2024-05-31 22:42 UTC
### Reproducing the behavior

```
let test = Name:new("test");
if test == "test" {
    //
}
```

If you make the comparison like this, it causes a Segmentation fault.

### System Settings

 - Bend: 0.2.18
 - Ubuntu 22.04.4 LTS on Windows 10 x86_64

### Additional context

[Source](https://github.com/HigherOrderCO/Bend/blob/main/src/fun/mod.rs#L248)

**Comment by LunaAmora** [comment] 2024-06-01 16:59
The code you showed here just executes fine the inside of the `if`, so i can't reproduce.

It shouldn't cause any segmentation fault, `Name` implements PartialEq for "&str", witch just compares the interned string to the string slice.

**Comment by developedby** [comment] 2024-06-04 11:56
Closing since we couldn't reproduce

**Closed by developedby** 2024-06-04 11:56 UTC
