### ISSUE TITLE
Segmentation fault with `run-c`

### ISSUE THREAD

**Issue by gabriel-gehrke** [HigherOrderCO/Bend#397] opened 2024-05-19 10:32 UTC
**Describe the bug**

I have implemented an algorithm that works as expected when executing it using `bend run`, but a segmentation fault occurs when I run it using `bend run-c`, or when I first generate C, compile that using clang and try to run it.

Specifically, `bend run sat.bend` gives me:
```
Result: "UNSAT"
```

On the other hand, `bend run-c sat.bend` shows:
```
Errors:
Error reading result from hvm. Output :
signal: 11 (SIGSEGV) (core dumped)
```

**To Reproduce**

Run `bend run-c sat.bend`.

I have attached the code (as .txt) here:
[sat.bend.txt](https://github.com/HigherOrderCO/Bend/files/15368994/sat.bend.txt)
I have also attached the generated hvm code here:
[sat.hvm.txt](https://github.com/HigherOrderCO/Bend/files/15368996/sat.hvm.txt)

**Desktop:**
 - OS:  Linux (Fedora 40)
 - CPU: Ryzen 9 5900X (x86_64)
 - bend-lang 0.2.7

**Comment by developedby** [comment] 2024-05-19 12:13
Moving discussion to https://github.com/HigherOrderCO/HVM/issues/309

**Comment by 0073-sudo** [comment] 2024-05-20 18:49
you have jail broken device refurbished at best get a brand new run the rest is good

**Comment by 0073-sudo** [comment] 2024-05-20 18:50
one not run sorry

**Comment by developedby** [comment] 2024-08-21 11:04
Closing since this was caused by https://github.com/HigherOrderCO/HVM/issues/309

**Closed by developedby** 2024-08-21 11:04 UTC
Labels: bug, HVM
