### ISSUE TITLE
Can't create a function that has no arguments

### ISSUE THREAD

**Issue by vkobinski** [HigherOrderCO/Bend#497] opened 2024-05-25 03:16 UTC
### Reproducing the behavior

```
def test():
  return 2

def main():
  return test()
```

$ bend run test.bend
Result: test

### System Settings

 - Bend: 0.2.15
 - OS: Linux (Ubuntu 22.04)
 - GPU: RTX 3050

**Comment by developedby** [comment] 2024-05-25 10:44
Duplicate of #493

**Closed by developedby** 2024-05-25 10:44 UTC
