### ISSUE TITLE
Interfacing Bend with Rust code

### ISSUE THREAD

**Issue by skalimoi** [HigherOrderCO/Bend#409] opened 2024-05-20 07:30 UTC
Hi, 

Given that Bend is written in Rust, are there any examples (or is it even possible) to interface Bend code in Rust code? If not, is it planned?

Thanks

**Comment by developedby** [comment] 2024-05-20 08:28
This is planned, but not yet available. I'll be added after we add IO.
Duplicate of #350

**Comment by developedby** [comment] 2024-05-20 08:28
Most likely it'll be done through a C interface

**Closed by developedby** 2024-05-20 08:28 UTC
